linters:
  enable:
    - errcheck
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
linters-settings:
  gocyclo:
    min-complexity: 15
