openapi: 3.0.1
info:
  title: Document Understanding REST APIs Preview
  description: 'Digitization Service for reading all text from images or PDFs, supporting various OCR types, used on demand, defaulting to the in-house built UiPath Document OCR. Supported file types: JPEG, PNG, PDF and TIFF'
  version: "1.0"
paths:
  /digitize/start:
    post:
      tags:
        - Digitization
      summary: Start Digitization Operation
      description: "Creates a new digitization operation for the input file.\r\nTo monitor the status of the digitization operation and retrieve the result, use the \"Get Digitization Operation Status\" route."
      parameters:
        - name: api-version
          in: query
          description: Version of the APIs.
          required: true
          schema:
            enum:
              - "1"
            type: string
        - name: x-uipath-apply-ocr-on-pdf
          in: header
          description: 'Specify whether or not to apply OCR on PDFs. Defaults to **yes** if not specified. Supported options: **yes**, **no**, **auto**.'
        - name: x-uipath-ocr-type
          in: header
          description: 'Type of the OCR to be used. Defaults to **uipath** if not specified. Supported options: **uipath**, **uipath_cjk**, **microsoft**, **google**, **google_japanese**.'
        - name: x-uipath-ocr-url
          in: header
          description: URL of the OCR to be used. Defaults to the URL of the **uipath** OCR from the current region if not specified.
        - name: x-uipath-ocr-api-key
          in: header
          description: API Key of the OCR to be used. This header is not required when the OCR type is **uipath** or **uipath_cjk**.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file:
                style: form
      responses:
        "202":
          description: Digitization Operation Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UiPath.DocumentUnderstanding.Digitizer.Api.Controllers.Models.StartDigitizationResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UiPath.DocumentUnderstanding.Digitizer.Api.Infrastructure.ErrorResponse'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UiPath.DocumentUnderstanding.Digitizer.Api.Infrastructure.ErrorResponse'
        "401":
          description: Unauthorized
        "415":
          description: Unsupported media type
        "503":
          description: Service Unavailable
  /digitize/result/{operationId}:
    get:
      tags:
        - Digitization
      summary: Get Digitization Operation Result
      description: "Gets the status and result of the Digitization Operation with the given ID. The status can be one of: \"NotStarted\", \"Running\", \"Succeeded\", \"Failed\".\r\nWhen the status is \"Succeeded\", the result ([Document Object Model](https://docs.uipath.com/activities/docs/dom)) is also included in the response.\r\nWhen the status is \"Failed\", a detailed error message is also included in the response."
      parameters:
        - name: api-version
          in: query
          description: Version of the APIs.
          required: true
          schema:
            enum:
              - "1"
            type: string
        - name: operationId
          in: path
          description: ID of the Digitization Operation.
          required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UiPath.DocumentUnderstanding.Digitizer.Api.Controllers.Models.LegacyPublicGetDigitizeJobResponse'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UiPath.DocumentUnderstanding.Digitizer.Api.Infrastructure.ErrorResponse'
        "401":
          description: Unauthorized
        "404":
          description: Operation not found
        "503":
          description: Service Unavailable
components:
  schemas:
    UiPath.DocumentUnderstanding.Digitizer.Api.Controllers.Models.LegacyPublicGetDigitizeJobResponse:
      type: object
      properties:
        status:
          title: Operation Status
          enum:
            - Succeeded
            - Failed
            - Running
            - NotStarted
          type: enum
          example: Succeeded
        error:
          $ref: '#/components/schemas/UiPath.DocumentUnderstanding.Digitizer.Api.Infrastructure.ErrorResponse'
        result:
          title: Document Object Model
          type: object
          properties:
            DocumentId:
              type: string
              example: 6d31c3a2-3446-4cc4-a122-fa5158b56f59
            ContentType:
              type: string
              example: image/bmp
            Length:
              type: integer
              example: 22
            Pages:
              type: object
              properties:
                PageIndex:
                  type: integer
                  example: 0
                Size:
                  type: object
                  oneOf:
                    - type: number
                      example: 0
                    - type: number
                      example: 0
                    - type: number
                      example: 501
                    - type: number
                      example: 199
                Sections:
                  type: object
                  properties:
                    IndexInText:
                      type: integer
                      example: 0
                    Language:
                      type: string
                      example: eng
                    Length:
                      type: integer
                      example: 22
                    Rotation:
                      type: string
                      example: None
                    SkewAngle:
                      type: number
                      example: -0.2
                    Type:
                      type: string
                      example: Paragraph
                    WordGroups:
                      type: object
                      properties:
                        IndexInText:
                          type: integer
                          example: 0
                        Length:
                          type: integer
                          example: 22
                        Type:
                          type: string
                          example: Other
                        Words:
                          type: object
                          properties:
                            Box:
                              type: object
                              oneOf:
                                - type: number
                                  example: 79
                                - type: number
                                  example: 52
                                - type: number
                                  example: 107
                                - type: number
                                  example: 41
                            Polygon:
                              type: object
                              oneOf:
                                - type: number
                                  example: 51.999992
                                - type: number
                                  example: 78.99998
                                - type: number
                                  example: 158.99997
                                - type: number
                                  example: 78.99998
                                - type: number
                                  example: 158.99997
                                - type: number
                                  example: 119.99998
                                - type: number
                                  example: 51.999992
                                - type: number
                                  example: 119.99997
                            IndexInText:
                              type: integer
                              example: 0
                            OcrConfidence:
                              type: integer
                              example: 1
                            Text:
                              type: string
                              example: Hello
                            VisualLineNumber:
                              type: integer
                              example: 0
                ProcessingSource:
                  type: string
                  example: Ocr
                IndexInText:
                  type: integer
                  example: 0
                TextLength:
                  type: integer
                  example: 22
                SkewAngle:
                  type: number
                  example: -0.2
          nullable: true
          example: '{"DocumentId":"6d31c3a2-3446-4cc4-a122-fa5158b56f59","ContentType":"image/bmp","Length":22,"Pages":[{"PageIndex":0,"Size":[0.0,0.0,501.0,199.0],"Sections":[{"IndexInText":0,"Language":"eng","Length":22,"Rotation":"None","SkewAngle":-0.2,"Type":"Paragraph","WordGroups":[{"IndexInText":0,"Length":22,"Type":"Other","Words":[{"Box":[1,2,3,4],"Polygon":[1,2,3,4,5,6,7,8],"IndexInText":0,"OcrConfidence":1.0,"Text":"Hello","VisualLineNumber":0}]}]}],"ProcessingSource":"Ocr","IndexInText":0,"TextLength":22,"SkewAngle":-0.2}]}'
        documentText:
          type: string
          nullable: true
        createdDateTime:
          type: string
          description: The time the operation was created
          format: date-time
          example: "2022-06-21T13:49:00.4971596Z"
        lastUpdatedDateTime:
          type: string
          description: The last time the operation was updated
          format: date-time
          example: "2022-06-21T13:49:10.1105179Z"
      additionalProperties: false
    UiPath.DocumentUnderstanding.Digitizer.Api.Controllers.Models.StartDigitizationResponse:
      type: object
      properties:
        operationId:
          type: string
          description: The Operation ID
          format: uuid
          example: ID of the digitization operation
      additionalProperties: false
    UiPath.DocumentUnderstanding.Digitizer.Api.Infrastructure.ErrorResponse:
      type: object
      properties:
        message:
          type: string
          nullable: true
        severity:
          type: string
          nullable: true
        code:
          type: string
          nullable: true
        parameters:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
  securitySchemes:
    oauth2:
      type: oauth2
      description: In order to enable access to the REST API you have to create an <A HREF="https://docs.uipath.com/automation-cloud/docs/managing-external-applications">external application</A> with the <b>Du.Digitization.Api</b> scope. After the external application is registered, you can use the App ID & App Secret with the <b>Du.Digitization.Api</b> scope in order to Authorize.
      flows:
        clientCredentials:
          tokenUrl: https://alpha.uipath.com/identity_/connect/token
          scopes:
            Du.Digitization.Api: Digitizer Api Scope
security:
  - oauth2:
      - Du.Digitization.Api
servers:
  - url: https://cloud.uipath.com/{organization}/{tenant}/du_/api/digitizer
    description: The production url
    variables:
      organization:
        description: The organization name (or id)
        default: my-org
      tenant:
        description: The tenant name (or id)
        default: my-tenant
