name: CI
on: [push]

env:
  UIPATHCLI_BASE_VERSION: "v2.0"
  GO_VERSION: "1.26.4"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      UIPATHCLI_VERSION: ${{ steps.version.outputs.UIPATHCLI_VERSION }}
    env:
      CGO_ENABLED: "0"
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # actions/checkout@v5
      - name: Setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Version
        id: version
        run: |
          UIPATHCLI_VERSION=$(./version.sh "$UIPATHCLI_BASE_VERSION")
          echo "UIPATHCLI_VERSION=$(echo $UIPATHCLI_VERSION)" >> $GITHUB_ENV
          echo "UIPATHCLI_VERSION=$(echo $UIPATHCLI_VERSION)" >> $GITHUB_OUTPUT
      - name: Build
        run: go build -ldflags="-X github.com/UiPath/uipathcli/utils.Version=$UIPATHCLI_VERSION" .
      - name: Lint
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.2
          golangci-lint run
      - name: Package
        run: ./build.sh && ./package.sh
      - name: Upload packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # actions/upload-artifact@v7
        with:
          name: packages
          path: build/packages/
          if-no-files-found: error

  test_linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # actions/checkout@v5
      - name: Setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Test
        run: go test -coverprofile="coverage.out" -coverpkg "$(go list github.com/UiPath/uipathcli/... | grep -v 'test' | tr '\n' ',')" ./...
      - name: Coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile="coverage.out" -service="github"

  test_windows:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # actions/checkout@v5
      - name: Setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Test
        run: go test ./...

  test_macos:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # actions/checkout@v5
      - name: Setup go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - name: Test
        run: go test ./...

  publish_pages:
    needs: [build, test_linux, test_windows, test_macos]
    permissions:
      contents: read
      pages: write
      id-token: write
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # actions/checkout@v5
      - name: Download packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # actions/download-artifact@v8
        with:
          name: packages
          path: build/packages/
      - name: Generate commands
        run: |
          tar -xzvf build/packages/uipathcli-linux-amd64.tar.gz
          ./uipath commands show > documentation/commands.json
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # actions/upload-pages-artifact@v5
        with:
          path: 'documentation'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # actions/deploy-pages@v5

  release:
    needs: [build, test_linux, test_windows, test_macos]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      UIPATHCLI_VERSION: ${{ needs.build.outputs.UIPATHCLI_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # actions/checkout@v5
      - name: Download packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # actions/download-artifact@v8
        with:
          name: packages
          path: build/packages/
      - name: Publish
        run: ./publish.sh "$UIPATHCLI_VERSION"
        env:
          GITHUB_TOKEN: ${{ github.token }}
